using System;
using System.IO;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using TimeSeriesAnalysis.Dynamic;

namespace KSpiceEngine
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("===================================================");
            Console.WriteLine(" K-Spice Engine - Phase 4B Formula Mapper Setup    ");
            Console.WriteLine("===================================================");

            // Use the JSON generated by our Phase 1 Python Extractor
            string extractedMapPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\..\..\..\data\extracted\KSpiceSystemMap.json"));

            if (!File.Exists(extractedMapPath))
            {
                Console.WriteLine($"[ERROR] System Map not found at {extractedMapPath}.");
                return;
            }

            try 
            {
                // 1. Build the Plant Simulator and extract the True MISO Map
                var plant = KSpiceModelFactory.BuildPlantFromMap(extractedMapPath, out List<JObject> tsaEquationsMap);
                
                // Export the Equation Mapping for the Python Visualizer
                string eqMapPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\..\..\..\output\diagrams\TSA_Equations.json"));
                Directory.CreateDirectory(Path.GetDirectoryName(eqMapPath));
                
                File.WriteAllText(eqMapPath, JsonConvert.SerializeObject(tsaEquationsMap, Formatting.Indented));
                Console.WriteLine($"\n[SUCCESS] TSA Equations Auto-Wired and Exported to: {eqMapPath}\n");

                // 2. Build the CSV Header mapping
                string csvPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\..\..\..\data\raw\KspiceSim.csv"));
                if (File.Exists(csvPath))
                {
                    string headerLine = File.ReadLines(csvPath).First();
                    var csvHeaders = new List<string>(headerLine.Split(',').Select(h => h.Trim()));
                    
                    var dynamicEqs = tsaEquationsMap.Cast<dynamic>().ToList();
                    var signalMap = DataSignalMapper.GenerateMapping(csvHeaders, dynamicEqs, extractedMapPath);

                    string mapOutPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\..\..\..\output\diagrams\SignalMapping.json"));
                    File.WriteAllText(mapOutPath, JsonConvert.SerializeObject(signalMap, Formatting.Indented));
                    Console.WriteLine($"[SUCCESS] Data DataSignalMapper Exported to: {mapOutPath}\n");
                    
                    // 3. Run Dynamic Simulation & TSA PID SysID Pipeline
                    Console.WriteLine("===================================================");
                    Console.WriteLine(" K-Spice Engine - Phase 4C Dynamic Plant Run       ");
                    Console.WriteLine("===================================================");
                    string validationOutPath = Path.GetFullPath(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, @"..\..\..\..\..\..\output\CS_Predictions.csv"));
                    
                    DynamicPlantRunner.RunPlantSimulations(
                        csvPath,
                        extractedMapPath,
                        eqMapPath,
                        mapOutPath,
                        validationOutPath
                    );
                    
                    Console.WriteLine($"\n[SUCCESS] C# Plant Simulations and SysID Complete.");
                    Console.WriteLine($"Predictions written to {validationOutPath}");
                }

            }
            catch (Exception ex)
            {
                Console.WriteLine("Exception Building Plant: " + ex.Message);
            }
        }
    }
}
